name: Docker Build
on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          tags: ${{ github.repository }}:latest
