name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Monero version (e.g., 0.18.3.4)'
        required: true
        type: string
      checksum:
        description: 'Checksum for the Monero binary (see linux-x64 @ https://www.getmonero.org/downloads/hashes.txt)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Dockerfile
        run: |
          sed -i "s/ENV VERSION=.*/ENV VERSION=${{ github.event.inputs.version }}/" Dockerfile
          sed -i "s/ENV CHECKSUM=.*/ENV CHECKSUM=${{ github.event.inputs.checksum }}/" Dockerfile

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ github.event.inputs.version }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Dockerfile
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update to Monero v${{ github.event.inputs.version }}"
            git push
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Monero Node v${{ github.event.inputs.version }}
          body: |
            Monero Node Docker image for Monero v${{ github.event.inputs.version }}
            
            Changes:
            - Updated to Monero v${{ github.event.inputs.version }}
            - Binary checksum: ${{ github.event.inputs.checksum }}
          draft: false
          prerelease: false

